package com.miaoshaproject.miaosha.dataobject;


import org.springframework.stereotype.Repository;

@Repository
public class UserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infoo.id
     *
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infoo.name
     *
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infoo.gender
     *
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infoo.age
     *
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infoo.telephone
     *
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infoo.register_mode
     *
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    private String registerMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_infoo.third_party_id
     *
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    private String thirdPartyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infoo.id
     *
     * @return the value of user_infoo.id
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infoo.id
     *
     * @param id the value for user_infoo.id
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infoo.name
     *
     * @return the value of user_infoo.name
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infoo.name
     *
     * @param name the value for user_infoo.name
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infoo.gender
     *
     * @return the value of user_infoo.gender
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infoo.gender
     *
     * @param gender the value for user_infoo.gender
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infoo.age
     *
     * @return the value of user_infoo.age
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infoo.age
     *
     * @param age the value for user_infoo.age
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infoo.telephone
     *
     * @return the value of user_infoo.telephone
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infoo.telephone
     *
     * @param telephone the value for user_infoo.telephone
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infoo.register_mode
     *
     * @return the value of user_infoo.register_mode
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public String getRegisterMode() {
        return registerMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infoo.register_mode
     *
     * @param registerMode the value for user_infoo.register_mode
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public void setRegisterMode(String registerMode) {
        this.registerMode = registerMode == null ? null : registerMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infoo.third_party_id
     *
     * @return the value of user_infoo.third_party_id
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infoo.third_party_id
     *
     * @param thirdPartyId the value for user_infoo.third_party_id
     * @mbggenerated Tue Mar 19 14:49:59 CST 2019
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }
}